CONNECT METODI/METODI@//localhost:1521/ORCLCDB;
CREATE TABLE "METODI"."USERS" 
   (	"ID" NUMBER(30,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"IS_ADMIN" NUMBER(1,0) NOT NULL ENABLE, 
	"DATE_CREATED" TIMESTAMP (6), 
	"DATE_EDITED" TIMESTAMP (6), 
	"CREATOR_ID" NUMBER(30,0), 
	"EDITOR_ID" NUMBER(30,0), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;
CREATE TABLE "METODI"."TEAMS" 
   (	"ID" NUMBER(30,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"DATE_CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATE_EDITED" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"EDITOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	 CONSTRAINT "TEAMS_PK" PRIMARY KEY ("ID")
	  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;
CREATE TABLE "METODI"."PROJECTS" 
   (	"ID" NUMBER(30,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"DATE_CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATE_EDITED" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"EDITOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	 CONSTRAINT "PROJECTS_PK" PRIMARY KEY ("ID")
	  USING INDEX (CREATE UNIQUE INDEX "METODI"."PROJECTS2_PK" ON "METODI"."PROJECTS" ("ID") 
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "SYSTEM" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;
CREATE TABLE "METODI"."TASKS" 
   (	"ID" NUMBER(30,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"DATE_CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATE_EDITED" TIMESTAMP (6) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER(30,0), 
	"CREATOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"EDITOR_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"ASSIGNEE_ID" NUMBER(30,0) NOT NULL ENABLE, 
	 CONSTRAINT "TASKS_PK" PRIMARY KEY ("ID")
	  USING INDEX (CREATE UNIQUE INDEX "METODI"."TASKS2_PK" ON "METODI"."TASKS" ("ID") 
      PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "SYSTEM" )  ENABLE, 
	  CONSTRAINT "PROJECTS_FK1" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "METODI"."PROJECTS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;	
CREATE TABLE "METODI"."WORKLOGS" 
   (	"ID" NUMBER(30,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TASK_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(30,0) NOT NULL ENABLE, 
	"HOURS_SPENT" NUMBER(30,0) NOT NULL ENABLE, 
	"DATE_WORKED" DATE NOT NULL ENABLE, 
	 CONSTRAINT "WORKLOGS_PK" PRIMARY KEY ("ID")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "TASK_ID_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "METODI"."TASKS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;
CREATE TABLE "METODI"."TEAM_USER" 
   (	"TEAM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"USER_ID" NUMBER(*,0), 
	 CONSTRAINT "USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "METODI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "TEAM_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "METODI"."TEAMS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;
CREATE TABLE "METODI"."TEAM_PROJECT" 
   (	"TEAM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER(*,0), 
	 CONSTRAINT "TEAM_ON_PROJECT_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "METODI"."TEAMS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "TEAM_PROJECT_FK1" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "METODI"."PROJECTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
	NOCOMPRESS LOGGING
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SYSTEM" ;